__include__:
  - ./dfine_l_rgbt_aic.yml

output_dir: runs/e10f_dfine_l_rgbt_all

train_dataloader:
  dataset:
    ann_file: data/prepared/dfine/all_train_balanced.json
    transforms:
      policy:
        epoch: 25
  collate_fn:
    stop_epoch: 25
    ema_restart_decay: 0.9999

optimizer:
  type: AdamW
  params:
    - {params: '^(?=.*backbone.input_adapter).*$', lr: 0.0000625}
    - {params: '^(?=.*backbone)(?!.*(?:input_adapter|norm|bn)).*$', lr: 0.0000015625}
    - {params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$', weight_decay: 0.0}
  lr: 0.00003125
  betas: [0.9, 0.999]
  weight_decay: 0.000125

epochs: 30
lr_scheduler:
  type: MultiStepLR
  milestones: [27]
  gamma: 0.1
lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 200
